languge: java

jdk:
  -openjdk15

sudo: false

notifications:
  email:
    recipients:
      - rke19922802@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

env:
