languge: java
jdk:
  -openjdk14

sudo: false

before_install:
  - cd java

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - rke19922802@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
       -CODECOV_TOKEN= "0abc78c5-1066-4938-80c1-e9d781137238"
